const MENU_ROUTES = {
  login: '/',
  home: '/home',
  users: '/usuarios',
  creatures: '/criaturas',
  tags: '/tags',
  locations: '/locais',
  races: '/racas',
  eras: '/eras',
  events: '/eventos',
  divinities: '/divindades',
  characters: '/personagens',
  organizations: '/organizacoes',
  families: '/familias',
  weapons: '/armas',
  traits: '/tracos',
  armors: '/armaduras',
  accessories: '/acessorios',
  shields: '/escudos',
  materials: '/materiais',
  consumables: '/consumiveis',
  ammunition: '/municoes',
  rules: '/regras',
  skills: '/pericias',
  conditions: '/condicoes',
  utilities: '/utilitarios',
  trainings: '/treinamentos',
  talents: '/talentos',
  characteristics: '/caracteristicas',
  techniques: '/tecnicas',
  spells: '/magias',
  campaigns: '/campanhas',
  sheets: '/fichas',
  biographies: '/biografias',
  enchantments: '/encantamentos',
  enhancements: '/aprimoramentos',
};

export const APP_ROUTES = {
  private: {
    home: MENU_ROUTES.home,
    users: MENU_ROUTES.users,
    creatures: MENU_ROUTES.creatures,
    tags: MENU_ROUTES.tags,
    locations: MENU_ROUTES.locations,
    races: MENU_ROUTES.races,
    eras: MENU_ROUTES.eras,
    events: MENU_ROUTES.events,
    divinities: MENU_ROUTES.divinities,
    characters: MENU_ROUTES.characters,
    organizations: MENU_ROUTES.organizations,
    families: MENU_ROUTES.families,
    weapons: MENU_ROUTES.weapons,
    traits: MENU_ROUTES.traits,
    armors: MENU_ROUTES.armors,
    accessories: MENU_ROUTES.accessories,
    shields: MENU_ROUTES.shields,
    materials: MENU_ROUTES.materials,
    consumables: MENU_ROUTES.consumables,
    ammunition: MENU_ROUTES.ammunition,
    rules: MENU_ROUTES.rules,
    skills: MENU_ROUTES.skills,
    conditions: MENU_ROUTES.conditions,
    utilities: MENU_ROUTES.utilities,
    trainings: MENU_ROUTES.trainings,
    talents: MENU_ROUTES.talents,
    characteristics: MENU_ROUTES.characteristics,
    techniques: MENU_ROUTES.techniques,
    spells: MENU_ROUTES.spells,
    campaigns: MENU_ROUTES.campaigns,
    campaignDetails: (id: string) => `${MENU_ROUTES.campaigns}/${id}`,
    sheets: MENU_ROUTES.sheets,
    sheetDetails: (id: string) => `${MENU_ROUTES.sheets}/${id}`,
    biographies: MENU_ROUTES.biographies,
    enchantments: MENU_ROUTES.enchantments,
    enhancements: MENU_ROUTES.enhancements,
  },
  public: {
    login: MENU_ROUTES.login,
  },
};
