const MENU_ROUTES = {
  login: '/',
  home: '/home',
  users: '/usuarios',
  creatures: '/criaturas',
  tags: '/tags',
  locations: '/locais',
  races: '/racas',
  eras: '/eras',
  events: '/eventos',
  divinities: '/divindades',
  characters: '/personagens',
  organizations: '/organizacoes',
  families: '/familias',
  equipment: '/equipamentos',
  materials: '/materiais',
  consumables: '/consumiveis',
  ammunition: '/municoes',
  rules: '/regras',
  skills: '/pericias',
  conditions: '/condicoes',
};

export const APP_ROUTES = {
  private: {
    home: MENU_ROUTES.home,
    users: MENU_ROUTES.users,
    creatures: MENU_ROUTES.creatures,
    tags: MENU_ROUTES.tags,
    locations: MENU_ROUTES.locations,
    races: MENU_ROUTES.races,
    eras: MENU_ROUTES.eras,
    events: MENU_ROUTES.events,
    divinities: MENU_ROUTES.divinities,
    characters: MENU_ROUTES.characters,
    organizations: MENU_ROUTES.organizations,
    families: MENU_ROUTES.families,
    equipment: MENU_ROUTES.equipment,
    materials: MENU_ROUTES.materials,
    consumables: MENU_ROUTES.consumables,
    ammunition: MENU_ROUTES.ammunition,
    rules: MENU_ROUTES.rules,
    skills: MENU_ROUTES.skills,
    conditions: MENU_ROUTES.conditions,
  },
  public: {
    login: MENU_ROUTES.login,
  },
};
