export enum LinkableEntityType {
  USER = 'user',
  CREATURE = 'creature',
  TAG = 'tag',
  LOCATION = 'location',
  RACE = 'race',
  ERA = 'era',
  EVENT = 'event',
  DIVINITY = 'divinity',
  CHARACTER = 'character',
  ORGANIZATION = 'organization',
  FAMILY = 'family',
  EQUIPMENT = 'equipment',
  MATERIAL = 'material',
  CONSUMABLE = 'consumable',
  AMMUNITION = 'ammunition',
  RULE = 'rule',
}
